"on":
  release:
    types:
      - published
name: Notify users
jobs:
  notify:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: node bin/notify-users
        env:
          PRIVATE_KEY: ${{ secrets.OCTOKIT_ROUTES_APP_PRIVATE_KEY }}
          VERSION: ${{ github.event.release.tag_name }}
