"on":
  push:
    branches:
      - master
      - beta
name: Release
jobs:
  build:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run build
      - run: ls dist/
      - run: npx semantic-release --debug
        env:
          GITHUB_TOKEN: ${{ secrets.OCTOKITBOT_PAT_FOR_SEMANTIC_RELEASE }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
