"on":
  - push
  - pull_request
name: Test
jobs:
  npmCi:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: lts/*
      - run: npm ci
      - run: npm run routes:lint
      - run: npm run lint
      - run: npm run test:ci
